# Generated by Django 4.1.6 on 2023-05-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_productdb_alter_categorydb_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorydb',
            name='Typeof',
        ),
    ]
