# Generated by Django 3.2.10 on 2023-05-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_remove_categorydb_typeof'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Namee', models.CharField(blank=True, max_length=100, null=True)),
                ('Categorynamee', models.CharField(blank=True, max_length=100, null=True)),
                ('Pricee', models.CharField(blank=True, max_length=100, null=True)),
                ('Sizee', models.CharField(blank=True, max_length=100, null=True)),
                ('Colorr', models.CharField(blank=True, max_length=100, null=True)),
                ('Typee', models.CharField(blank=True, max_length=100, null=True)),
                ('Aboutt', models.CharField(blank=True, max_length=100, null=True)),
                ('Imagee', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
    ]
