# Generated by Django 3.2.10 on 2023-05-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_itemdb_productname'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='Productname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
