# Generated by Django 3.2.10 on 2023-05-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_productdb_productname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdb',
            name='Productname',
        ),
    ]
