# Generated by Django 3.2.10 on 2023-06-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_remove_productdb_productname'),
    ]

    operations = [
        migrations.CreateModel(
            name='generesdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Generess', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
