# Generated by Django 3.2.10 on 2023-05-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customerdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=30, null=True)),
                ('Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('Password', models.CharField(blank=True, max_length=100, null=True)),
                ('Confirm_password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
