# Generated by Django 3.2.10 on 2023-05-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('names', models.CharField(blank=True, max_length=30, null=True)),
                ('prices', models.IntegerField(blank=True, null=True)),
                ('quantities', models.CharField(blank=True, max_length=30, null=True)),
                ('totalprices', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customerdetails',
            name='Confirm_password',
        ),
    ]
