# Generated by Django 3.2.10 on 2023-05-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0002_auto_20230524_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='abouts',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
