# Generated by Django 3.2.10 on 2023-05-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0004_remove_cartdb_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
