# Generated by Django 3.2.10 on 2023-05-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0005_cartdb_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cartdb',
        ),
    ]
