# Generated by Django 3.2.10 on 2023-05-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0006_delete_cartdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='carttdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('names', models.CharField(blank=True, max_length=100, null=True)),
                ('prices', models.IntegerField(blank=True, max_length=100, null=True)),
                ('quantities', models.IntegerField(blank=True, max_length=100, null=True)),
                ('sizes', models.CharField(blank=True, max_length=100, null=True)),
                ('totalprices', models.IntegerField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
