# Generated by Django 3.2.10 on 2023-05-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0007_carttdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carttdb',
            name='images',
        ),
    ]
