# Generated by Django 3.2.10 on 2023-05-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0008_remove_carttdb_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartnew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(blank=True, max_length=100, null=True)),
                ('prices', models.IntegerField(blank=True, max_length=100, null=True)),
                ('quantities', models.IntegerField(blank=True, max_length=100, null=True)),
                ('sizes', models.CharField(blank=True, max_length=100, null=True)),
                ('totalprices', models.IntegerField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='carttdb',
        ),
    ]
