# Generated by Django 3.2.10 on 2023-05-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0009_auto_20230529_1007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cartnew',
        ),
    ]
