# Generated by Django 3.2.10 on 2023-05-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0012_newcartdb_userr'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='Confirmpassword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
