# Generated by Django 3.2.10 on 2023-06-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0014_checkoutdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcartdb',
            name='Imagee',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
